# Generated by Django 4.0.1 on 2022-02-24 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bedrooms',
            field=models.IntegerField(default=0),
        ),
    ]
